services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: argos-app
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: argos-db
    environment:
      MYSQL_DATABASE: inpex_id
      MYSQL_ROOT_PASSWORD: T3lt3x@Admin
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
